[package]
name = "crun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
cron = "0.12.0"
uuid = { version = "1.2.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
